### ISSUE TITLE
AssertionError: ERROR: Call to stanford_ner exited with a non-zero code status.

### ISSUE THREAD

**Issue by safat006** [philipperemy/information-extraction-with-dominating-rules#1]
Hello, 

I run the code on both mac and windows pc. But I'm getting the same error. Would you please tell why this is happening! Do I need to download any other .jar files?

**Comment by philipperemy** [comment]
Let me try that!

**Comment by philipperemy** [comment]
Ok I could reproduce the bug. I pushed a new fix.

Please make a fresh `git clone --recursive` of the project and try again.

**Comment by philipperemy** [comment]
Should now be ok
