### ISSUE TITLE
Graph visulization not here

### ISSUE THREAD

**Issue by nidhigoyal123** [philipperemy/information-extraction-with-dominating-rules#2]
I can't able to visualize the graph as shown in readme.md

**Comment by ManishManu1** [comment]
I'm facing the same problem.

**Comment by OlehKitGit** [comment]
me too.

**Comment by philipperemy** [comment]
Thanks guys I'm going to have a look!

**Comment by philipperemy** [comment]
@OlegKitGit @ManishManu1 
I can't download http://nlp.stanford.edu/software/stanford-ner-2015-12-09.zip
Can one of you guys zip the whole source folder and send it to me via Google Drive? Thanks

**Comment by chankeypathak** [comment]
@philipperemy Stanford nlp website is down since past 2 days.

**Comment by philipperemy** [comment]
@chankeypathak Thanks for the info! I could find a local copy of those files. Will package all of that :)

**Comment by philipperemy** [comment]
Guys should be good now. @OlegKitGit @ManishManu1 @nidhigoyal123
